/*
 * BoxFoldersRTX.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BoxFoldersRTX.Standard;
using BoxFoldersRTX.Standard.Utilities;


namespace BoxFoldersRTX.Standard.Models
{
    public class Parent : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }
    }
} 