/*
 * BoxFoldersRTX.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using BoxFoldersRTX.Standard.Controllers;
using BoxFoldersRTX.Standard.Http.Client;
using BoxFoldersRTX.Standard.Utilities;

namespace BoxFoldersRTX.Standard
{
    public partial class BoxFoldersRTXClient
    {

        /// <summary>
        /// Singleton access to Folders controller
        /// </summary>
        public FoldersController Folders
        {
            get
            {
                return FoldersController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public BoxFoldersRTXClient() { }
        #endregion
    }
}